export const VISIBILITY_FILTERS = {
  CREATION_DATE_DESC: 'CREATION_DATE_DESC',
  CREATION_DATE_ASC: 'CREATION_DATE_ASC',
  FINISH_DATE_ASC: 'FINISH_DATE_ASC',
  FINISH_DATE_DESC: 'FINISH_DATE_DESC',
  STATUS_ATR_LIB: 'STATUS_ATR_LIB',
  STATUS_LIB_ATR: 'STATUS_LIB_ATR',
};
